CREATE TABLE projects (
  project_id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  status VARCHAR(255) DEFAULT NULL
);